### PR TITLE
Wire uglify options

### PR DESCRIPTION
**Pull request by arichiardi**
I was in need of some debugging so I wired up the options in this PR.

I hope everything is good! :smile:

### CODE REVIEW

**Comment by nha** [comment]
@arichiardi Thanks a lot! I will review it this weekend and cut a new release.

**Comment by nha** [comment]
It seems the tests are failing.
I updated the repo settings so that they run for the PRs as well, but you can run them manually too with `boot test`. Would you like correct them?

**Comment by arichiardi** [comment]
Of course 😀 I will have a look.

**Comment by arichiardi** [comment]
I checked and there is an error:

```
:cause "Error"
 :via
 [{:type javax.script.ScriptException
   :message "Error in <eval> at line number 1 at column number 27293"
   :at [jdk.nashorn.api.scripting.NashornScriptEngine throwAsScriptException "NashornScriptEngine.java" 470]}
  {:type jdk.nashorn.internal.runtime.ECMAException
   :message "Error"
   :at [jdk.nashorn.internal.runtime.ECMAException create "ECMAException.java" 113]}]
```

Which I have never seen before.

The other is a byte number diff:

``` 
can minify several files can minify a directory
expected: {:errors (),
           :warnings (),
           :sources ("arrays.js" "blocks.js" "conditionals.js"),
           :target "all.min.js",
           :original-size 413,
           :compressed-size 158,
           :sources-gzipped-size 211,
           :target-gzipped-size 127}
  actual: {:errors (),
           :warnings (),
           :sources ("arrays.js" "conditionals.js" "blocks.js"),
           :target "all.min.js",
           :original-size 413,
           :compressed-size 158,
           :sources-gzipped-size 212,
           :target-gzipped-size 122}
    diff: - {:target-gzipped-size 127,
             :sources-gzipped-size 211,
             :sources [nil "blocks.js" "conditionals.js"]}
          + {:target-gzipped-size 122,
             :sources-gzipped-size 212,
             :sources [nil "conditionals.js" "blocks.js"]}
```

Any clue?

**Comment by nha** [comment]
@arichiardi Not sure yet just by looking at it, Nashorn errors are not really readable.

At this point, I think it might be easier to:

- merge your first commit
- wait for the new unified UglifyJS API: https://github.com/mishoo/UglifyJS2/pull/1366 and propose the same options

What do you think?

Thanks a ton for making this PR, the first ever on one of my projects :1st_place_medal: . Really appreciated!

**Comment by arichiardi** [comment]
Ahahah no problem! This is a very useful task and like any useful thing shared and open source, it will get more love I am sure 😀

Your proposal sounds good,  I will remove the second commit then and change the title.

**Comment by nha** [comment]
I took the first commit and put it on master, closing this PR for now.
Thanks!

**Comment by arichiardi** [comment]
Thanks! I did not have time to do this myself.

**Pull request closed without merging**
